engApi: 
  port: ":8090"

db: 
  openDriver: "godror"
  connection: 
    "user=\"dbeng200\" 
     password=\"rucom555\" 
     connectString=\"10.2.1.98:1571/RUBRAM?expire_timconnect_time=2\"
     sysdba=0
     sysoper=0
     poolMinSessions=1
     poolMaxSessions=1000
     poolIncrement=1
     standaloneConnection=0
     enableEvents=0
     heterogeneousPool=0
     externalAuth=0
     prelim=0
     poolWaitTimeout=5m
     poolSessionMaxLifetime=1h
     poolSessionTimeout=30s
     timezone=\"local\""
  

